package com.netease.nemo.model.po;

import java.util.Date;

/**
 * 数据库表 : gift
 * 
 * @author : auto generated by mybatis generator
 */
public class Gift {
    /**
     * 
     */
    private Long id;

    /**
     * 礼物名称
     */
    private String giftName;

    /**
     * 礼物描述
     */
    private String giftDesc;

    /**
     * 礼物价值云币金额
     */
    private Long cloudCoin;

    /**
     * 礼物是否有效：-1.无效，1.有效
     */
    private Byte status;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGiftName() {
        return giftName;
    }

    public void setGiftName(String giftName) {
        this.giftName = giftName == null ? null : giftName.trim();
    }

    public String getGiftDesc() {
        return giftDesc;
    }

    public void setGiftDesc(String giftDesc) {
        this.giftDesc = giftDesc == null ? null : giftDesc.trim();
    }

    public Long getCloudCoin() {
        return cloudCoin;
    }

    public void setCloudCoin(Long cloudCoin) {
        this.cloudCoin = cloudCoin;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}