package com.netease.nemo.model.po;

import java.util.Date;

/**
 * 数据库表 : user_reward
 * 
 * @author : auto generated by mybatis generator
 */
public class UserReward {
    /**
     * 
     */
    private Long id;

    /**
     * 打赏者账号
     */
    private String userUuid;

    /**
     * 礼物名称
     */
    private Long giftId;

    /**
     * 礼物个数
     */
    private Integer giftCount;

    /**
     * 礼物价值云币金额
     */
    private Long cloudCoin;

    /**
     * 被打赏者账号
     */
    private String target;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserUuid() {
        return userUuid;
    }

    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    public Long getGiftId() {
        return giftId;
    }

    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    public Integer getGiftCount() {
        return giftCount;
    }

    public void setGiftCount(Integer giftCount) {
        this.giftCount = giftCount;
    }

    public Long getCloudCoin() {
        return cloudCoin;
    }

    public void setCloudCoin(Long cloudCoin) {
        this.cloudCoin = cloudCoin;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}