package com.netease.nemo.game.model.po;

import java.util.Date;

/**
 * 数据库表 : game_record_history
 * 
 * @author : auto generated by mybatis generator
 */
public class GameRecordHistory {
    /**
     * 
     */
    private Long id;

    /**
     * 游戏唯一记录编号
     */
    private Long gameRecordId;

    /**
     * 直播唯一记录
     */
    private Long liveRecordId;

    /**
     * 虚拟房间编号
     */
    private String roomUuid;

    /**
     * 游戏房间创建者
     */
    private String gameCreator;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * 游戏状态0：待开始 1游戏中 2 游戏结束
     */
    private Integer gameStatus;

    /**
     * 游戏Id
     */
    private String gameId;

    /**
     * 游戏名称
     */
    private String gameName;

    /**
     * 游戏描述
     */
    private String gameDesc;

    /**
     * 游戏背景图
     */
    private String thumbnail;

    /**
     * 游戏规则
     */
    private String rule;

    /**
     * 虚拟房间唯一编号
     */
    private String roomArchiveId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLiveRecordId() {
        return liveRecordId;
    }

    public void setLiveRecordId(Long liveRecordId) {
        this.liveRecordId = liveRecordId;
    }

    public String getRoomUuid() {
        return roomUuid;
    }

    public void setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid == null ? null : roomUuid.trim();
    }

    public String getGameCreator() {
        return gameCreator;
    }

    public void setGameCreator(String gameCreator) {
        this.gameCreator = gameCreator == null ? null : gameCreator.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getGameStatus() {
        return gameStatus;
    }

    public void setGameStatus(Integer gameStatus) {
        this.gameStatus = gameStatus;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    public String getGameDesc() {
        return gameDesc;
    }

    public void setGameDesc(String gameDesc) {
        this.gameDesc = gameDesc == null ? null : gameDesc.trim();
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    public String getRule() {
        return rule;
    }

    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    public String getRoomArchiveId() {
        return roomArchiveId;
    }

    public void setRoomArchiveId(String roomArchiveId) {
        this.roomArchiveId = roomArchiveId == null ? null : roomArchiveId.trim();
    }

    public Long getGameRecordId() {
        return gameRecordId;
    }

    public void setGameRecordId(Long gameRecordId) {
        this.gameRecordId = gameRecordId;
    }
}