package com.netease.nemo.game.model.po;

import java.util.Date;

/**
 * 数据库表 : game_report
 * 
 * @author : auto generated by mybatis generator
 */
public class GameReport {
    /**
     * 
     */
    private Long id;


    /**
     * 每局游戏唯一标识
     */
    private Long gameRecordId;

    /**
     * 上报数据
     */
    private String reportMsg;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGameRecordId() {
        return gameRecordId;
    }

    public void setGameRecordId(Long gameRecordId) {
        this.gameRecordId = gameRecordId;
    }

    public String getReportMsg() {
        return reportMsg;
    }

    public void setReportMsg(String reportMsg) {
        this.reportMsg = reportMsg == null ? null : reportMsg.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}