package com.netease.nemo.entlive.model.po;

import com.netease.nemo.entlive.dto.LiveRecordDto;

import java.util.Date;

/**
 * 数据库表 : chorus_record
 * 
 * @author : auto generated by mybatis generator
 */
public class ChorusRecord {
    /**
     * 
     */
    private Long id;

    /**
     * 合唱编号
     */
    private String chorusId;

    /**
     * 虚拟房间编号
     */
    private String roomUuid;

    /**
     * 虚拟房间名称
     */
    private String roomName;

    /**
     * 点歌编号
     */
    private Long orderId;

    /**
     * 直播编号
     */
    private Long liveRecordId;

    /**
     * 主唱编号
     */
    private String leaderUuid;

    /**
     * 副唱编号
     */
    private String assistantUuid;

    /**
     * 状态：1.有效，-1.无效
     */
    private Integer status;

    /**
     * 0:邀请中 1:合唱中 2:拒绝 3:取消 4:合唱结束 5:同意合唱
     */
    private Integer state;

    /**
     * 主唱的设备参数，判断走串行还是实时合唱
     * {
     *     "playDelay":30,    //播放延时，单位：ms
     *     "rtt":20,    //rtt值，单位：ms
     *     "wiredHeadset":1    //有线耳机，1: 有线耳机，0: 非有线耳机
     * }
     * **/
    private String leaderDeviceParam;

    /**
     * 副唱的设备参数，判断走串行还是实时合唱
     * {
     *     "playDelay":30,    //播放延时，单位：ms
     *     "rtt":20,    //rtt值，单位：ms
     *     "wiredHeadset":1    //有线耳机，1: 有线耳机，0: 非有线耳机
     * }
     * **/
    private String assistantDeviceParam;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    public ChorusRecord() {
    }

    public ChorusRecord(String chorusId, LiveRecordDto liveRecordDto, String leaderUuid, Long orderId, Integer state) {
        this.chorusId = chorusId;
        this.orderId = orderId;
        this.leaderUuid = leaderUuid;
        this.state = state;

        this.roomName = liveRecordDto.getRoomName();
        this.roomUuid = liveRecordDto.getRoomUuid();
        this.liveRecordId = liveRecordDto.getId();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChorusId() {
        return chorusId;
    }

    public void setChorusId(String chorusId) {
        this.chorusId = chorusId == null ? null : chorusId.trim();
    }

    public String getRoomUuid() {
        return roomUuid;
    }

    public void setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid == null ? null : roomUuid.trim();
    }

    public String getRoomName() {
        return roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }


    public Long getLiveRecordId() {
        return liveRecordId;
    }

    public void setLiveRecordId(Long liveRecordId) {
        this.liveRecordId = liveRecordId;
    }

    public String getLeaderUuid() {
        return leaderUuid;
    }

    public void setLeaderUuid(String leaderUuid) {
        this.leaderUuid = leaderUuid == null ? null : leaderUuid.trim();
    }

    public String getAssistantUuid() {
        return assistantUuid;
    }

    public void setAssistantUuid(String assistantUuid) {
        this.assistantUuid = assistantUuid == null ? null : assistantUuid.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getLeaderDeviceParam() {
        return leaderDeviceParam;
    }

    public void setLeaderDeviceParam(String leaderDeviceParam) {
        this.leaderDeviceParam = leaderDeviceParam;
    }

    public String getAssistantDeviceParam() {
        return assistantDeviceParam;
    }

    public void setAssistantDeviceParam(String assistantDeviceParam) {
        this.assistantDeviceParam = assistantDeviceParam;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
}