package com.netease.nemo.entlive.model.po;

import com.netease.nemo.model.po.Gift;

import java.util.Date;

/**
 * 数据库表 : live_reward
 * 
 * @author : auto generated by mybatis generator
 */
public class LiveReward {
    /**
     * 
     */
    private Long id;

    /**
     * 直播编号
     */
    private Long liveRecordId;

    /**
     * NeRoom虚拟房间唯一编号
     */
    private String roomArchiveId;

    /**
     * NeRoom房间编号
     */
    private String roomUuid;

    /**
     * 帐号id
     */
    private String userUuid;

    /**
     * 礼物标号
     */
    private Long giftId;

    /**
     * 礼物价值云币金额
     */
    private Long cloudCoin;

    /**
     * 礼物个数
     */
    private Integer giftCount;

    /**
     * 被打赏者用户uuid
     */
    private String target;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;


    public static LiveReward buildReward(Long liveRecordId, String roomArchiveId, String roomUuid, String userUuid, String target, Gift gift, Integer giftCount) {
        LiveReward liveReward = new LiveReward();
        liveReward.setGiftId(gift.getId());
        liveReward.setCloudCoin(gift.getCloudCoin());
        liveReward.setRoomUuid(roomUuid);
        liveReward.setRoomArchiveId(roomArchiveId);
        liveReward.setUserUuid(userUuid);
        liveReward.setTarget(target);
        liveReward.setLiveRecordId(liveRecordId);
        liveReward.setGiftCount(giftCount);
        return liveReward;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLiveRecordId() {
        return liveRecordId;
    }

    public void setLiveRecordId(Long liveRecordId) {
        this.liveRecordId = liveRecordId;
    }

    public String getRoomArchiveId() {
        return roomArchiveId;
    }

    public void setRoomArchiveId(String roomArchiveId) {
        this.roomArchiveId = roomArchiveId == null ? null : roomArchiveId.trim();
    }

    public String getRoomUuid() {
        return roomUuid;
    }

    public void setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid == null ? null : roomUuid.trim();
    }

    public String getUserUuid() {
        return userUuid;
    }

    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    public Long getGiftId() {
        return giftId;
    }

    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    public Long getCloudCoin() {
        return cloudCoin;
    }

    public void setCloudCoin(Long cloudCoin) {
        this.cloudCoin = cloudCoin;
    }

    public Integer getGiftCount() {
        return giftCount;
    }

    public void setGiftCount(Integer giftCount) {
        this.giftCount = giftCount;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}