package com.netease.nemo.entlive.model.po;

import com.netease.nemo.entlive.enums.LiveEnum;
import com.netease.nemo.entlive.enums.StatusEnum;
import com.netease.nemo.entlive.parameter.CreateLiveParam;

import java.util.Date;

/**
 * 数据库表 : live_record
 *
 * @author : auto generated by mybatis generator
 */
public class LiveRecord {
    /**
     *
     */
    private Long id;

    /**
     * NeRoom虚拟房间唯一编号
     */
    private String roomArchiveId;

    /**
     * 虚拟房间编号
     */
    private String roomUuid;

    /**
     * 虚拟房间编号
     */
    private String roomName;

    /**
     * 主播账户编号
     */
    private String userUuid;

    /**
     * 直播主题
     */
    private String liveTopic;

    /**
     * 封面URL，如果传空则自动生成
     */
    private String cover;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * 直播状态：1.有效，-1.无效
     */
    private Integer status;

    /**
     * 直播状态，-1.结束, 0.未开始，1.直播中
     */
    private Integer live;

    /**
     * 直播类型 1.互动直播  2.语聊房，3. KTV
     */
    private Integer liveType;


    public LiveRecord() {
    }

    public LiveRecord(Long id, Integer live) {
        this.id = id;
        this.live = live;
    }

    public LiveRecord(Long liveRecordId, Integer live, int status) {
        this(liveRecordId, live);
        this.status = status;
    }

    public static LiveRecord builderLiveRecord(CreateLiveParam param, String userUuid, String roomUuid, String roomArchiveId) {
        LiveRecord liveRecord = new LiveRecord();
        liveRecord.setLiveType(param.getLiveType());
        liveRecord.setCover(param.getCover());
        liveRecord.setLiveTopic(param.getLiveTopic());
        liveRecord.setRoomUuid(roomUuid);
        liveRecord.setRoomArchiveId(roomArchiveId);
        liveRecord.setStatus(StatusEnum.VALID.getCode());
        liveRecord.setLive(LiveEnum.NOT_START.getCode());
        liveRecord.setUserUuid(userUuid);
        liveRecord.setRoomName(param.getRoomName());
        return liveRecord;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRoomArchiveId() {
        return roomArchiveId;
    }

    public void setRoomArchiveId(String roomArchiveId) {
        this.roomArchiveId = roomArchiveId == null ? null : roomArchiveId.trim();
    }

    public String getRoomUuid() {
        return roomUuid;
    }

    public void setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid == null ? null : roomUuid.trim();
    }

    public String getRoomName() {
        return roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    public String getUserUuid() {
        return userUuid;
    }

    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    public String getLiveTopic() {
        return liveTopic;
    }

    public void setLiveTopic(String liveTopic) {
        this.liveTopic = liveTopic == null ? null : liveTopic.trim();
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getLive() {
        return live;
    }

    public void setLive(Integer live) {
        this.live = live;
    }

    public Integer getLiveType() {
        return liveType;
    }

    public void setLiveType(Integer liveType) {
        this.liveType = liveType;
    }
}