package com.netease.nemo.entlive.model.po;

import java.util.Date;

/**
 * 数据库表 : order_song
 * 
 * @author : auto generated by mybatis generator
 */
public class OrderSong {
    /**
     * 
     */
    private Long id;

    /**
     * 直播唯一编号
     */
    private Long liveRecordId;

    /**
     * NeRoom虚拟房间唯一编号
     */
    private String roomArchiveId;

    /**
     * 关联roomUuid
     */
    private String roomUuid;

    /**
     * 用户编号
     */
    private String userUuid;

    /**
     * 歌曲编号
     */
    private String songId;

    /**
     * 歌曲名称
     */
    private String songName;

    /**
     * 歌曲封面
     */
    private String songCover;

    /**
     * 歌手
     */
    private String singer;

    /**
     * 封面URL
     */
    private String singerCover;

    /**
     * 歌曲时长时间
     */
    private Long songTime;

    /**
     * 版权来源：1：云音乐 2、咪咕
     */
    private Integer channel;

    /**
     * CANCEL(-1, "删除点歌"),
     * WAITING(0, "等待唱歌或者等待播放"),
     * PLAYING(1, "唱歌中或者播放中"),
     * PLAYED(2, "已唱或者已播放"),;
     */
    private Integer status;

    /**
     * 置顶时间
     */
    private Long setTopTime;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLiveRecordId() {
        return liveRecordId;
    }

    public void setLiveRecordId(Long liveRecordId) {
        this.liveRecordId = liveRecordId;
    }

    public String getRoomArchiveId() {
        return roomArchiveId;
    }

    public void setRoomArchiveId(String roomArchiveId) {
        this.roomArchiveId = roomArchiveId == null ? null : roomArchiveId.trim();
    }

    public String getRoomUuid() {
        return roomUuid;
    }

    public void setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid == null ? null : roomUuid.trim();
    }

    public String getUserUuid() {
        return userUuid;
    }

    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    public String getSongId() {
        return songId;
    }

    public void setSongId(String songId) {
        this.songId = songId == null ? null : songId.trim();
    }

    public String getSongName() {
        return songName;
    }

    public void setSongName(String songName) {
        this.songName = songName == null ? null : songName.trim();
    }

    public String getSongCover() {
        return songCover;
    }

    public void setSongCover(String songCover) {
        this.songCover = songCover == null ? null : songCover.trim();
    }

    public String getSinger() {
        return singer;
    }

    public void setSinger(String singer) {
        this.singer = singer == null ? null : singer.trim();
    }

    public String getSingerCover() {
        return singerCover;
    }

    public void setSingerCover(String singerCover) {
        this.singerCover = singerCover == null ? null : singerCover.trim();
    }

    public Long getSongTime() {
        return songTime;
    }

    public void setSongTime(Long songTime) {
        this.songTime = songTime;
    }

    public Integer getChannel() {
        return channel;
    }

    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getSetTopTime() {
        return setTopTime;
    }

    public void setSetTopTime(Long setTopTime) {
        this.setTopTime = setTopTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}