package com.netease.nemo.socialchat.po;

import com.netease.nemo.socialchat.parameter.openai.ArsReportParam;
import com.netease.nemo.util.gson.GsonIgnore;

import java.util.Date;

/**
 * 数据库表 : asr_report
 * 
 * @author : auto generated by mybatis generator
 */
public class AsrReport {
    /**
     * 
     */
    @GsonIgnore
    private Long id;

    /**
     * 房间编号
     */
    @GsonIgnore
    private String roomUuid;

    /**
     * 用户编号
     */
    private String userUuid;

    /**
     * 上报时间
     */
    private Long reportTime;

    /**
     * 上报内容
     */
    private String content;

    /**
     * 创建时间
     */
    @GsonIgnore
    private Date createTime;

    /**
     * 更新时间
     */
    @GsonIgnore
    private Date updateTime;

    public static AsrReport build(ArsReportParam param) {
        AsrReport asrReport = new AsrReport();
        asrReport.setContent(param.getContent());
        asrReport.setReportTime(param.getReportTime());
        asrReport.setRoomUuid(param.getRoomUuid());
        asrReport.setUserUuid(param.getUserUuid());
        return asrReport;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRoomUuid() {
        return roomUuid;
    }

    public void setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid == null ? null : roomUuid.trim();
    }

    public String getUserUuid() {
        return userUuid;
    }

    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    public Long getReportTime() {
        return reportTime;
    }

    public void setReportTime(Long reportTime) {
        this.reportTime = reportTime;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}